<section className="basic-grid">
      <div className="nes-container is-dark with-title is-primary">
      <h3 className="title">Ultra Grid</h3>
        <p className="title">1</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
      <div className="nes-container is-dark with-title is-primary">
        <p className="title">2</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
      <div className="nes-container is-dark with-title is-primary">
        <p className="title">3</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
      <div className="nes-container is-dark with-title is-primary">
        <p className="title">4</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
      <div className="nes-container is-dark with-title is-primary">
        <p className="title">5</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
      <div className="nes-container is-dark with-title is-primary">
        <p className="title">6</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
      <div className="nes-container is-dark with-title is-primary">
        <p className="title">7</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
      <div className="nes-container is-dark with-title is-primary">
        <p className="title">8</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
      <div className="nes-container is-dark with-title is-primary">
        <p className="title">9</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
      <div className="nes-container is-dark with-title is-primary">
        <p className="title">10</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
      <div className="nes-container is-dark with-title is-primary">
        <p className="title">11</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
      <div className="nes-container is-dark with-title is-primary">
        <p className="title">12</p>
        <p>Lorem lmpsum esto y eso</p>
      </div>
    </section>